# Generated by Django 3.0.3 on 2020-03-25 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=10)),
                ('connections', models.ManyToManyField(blank=True, default=None, null=True, to='connections.Connections')),
                ('users', models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
