# Generated by Django 3.0.3 on 2020-03-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_connectionurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connections',
            name='connection_pin',
        ),
    ]
