# Generated by Django 3.0.3 on 2020-03-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_remove_connections_connection_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='connection_pin',
            field=models.IntegerField(default=0),
        ),
    ]
